[config]
reload_apps = true

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty.conf"
output_path = "~/.config/ghostty/colors"

[templates.wofi]
input_path = "~/.config/matugen/templates/wofi.css"
output_path = "~/.config/wofi/colors.css"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"
