general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms("on")'
}

# Jika sedang di lockscreen (hyprlock), matikan layar setelah 90 detik
listener {
    timeout = 90
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")'
}

# Redupkan layar ke 10% sebelum terkunci (4 menit 30 detik)
listener {
    timeout = 270
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Kunci layar setelah 5 menit (300 detik)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Matikan layar setelah 5 menit 30 detik jika tidak terkunci manual
listener {
    timeout = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")' && brightnessctl -r
}
