#!/bin/bash

# Dynamically generate wofi background + CSS with current wallpaper as left panel
WALLPAPER=$(cat ~/.current_wallpaper 2>/dev/null)
STYLE_DIR="$HOME/.config/wofi"
GENERATED_STYLE="$STYLE_DIR/style-generated.css"
COMPOSITE="$HOME/.cache/wofi-bg.png"
CACHE_MARKER="$HOME/.cache/wofi-bg-src"

# Fallback if no wallpaper is set
if [ -z "$WALLPAPER" ] || [ ! -f "$WALLPAPER" ]; then
    WALLPAPER="$HOME/.cache/wallpaper_rn.png"
fi

# Only regenerate composite if wallpaper changed
CACHED_SRC=""
[ -f "$CACHE_MARKER" ] && CACHED_SRC=$(cat "$CACHE_MARKER")

if [ "$CACHED_SRC" != "$WALLPAPER" ] || [ ! -f "$COMPOSITE" ]; then
    # Use actual monitor resolution
    MON_W=$(hyprctl monitors -j 2>/dev/null | jq -r '.[0].width // 1920')
    MON_H=$(hyprctl monitors -j 2>/dev/null | jq -r '.[0].height // 1080')

    # Window size: 45% x 50% of monitor
    W=$(( MON_W * 45 / 100 ))
    H=$(( MON_H * 50 / 100 ))
    WP_W=$(( W * 38 / 100 ))  # wallpaper panel ~38% of window

    magick "$WALLPAPER" -resize "${WP_W}x${H}^" -gravity center -extent "${WP_W}x${H}" \
        \( -size "$(( W - WP_W ))x${H}" xc:"#1e1e1e" \) \
        +append -quality 85 "$COMPOSITE" 2>/dev/null

    echo "$WALLPAPER" > "$CACHE_MARKER"
fi

# Recalculate WP_W for CSS (in case we skipped regeneration)
MON_W=$(hyprctl monitors -j 2>/dev/null | jq -r '.[0].width // 1920')
W=$(( MON_W * 45 / 100 ))
WP_W=$(( W * 38 / 100 ))

# Generate the CSS
cat > "$GENERATED_STYLE" << CSSEOF
/* === Wofi - Wallpaper Panel Style === */
/* Auto-generated by launch.sh — do not edit manually */

window {
    background-color: #1e1e1e;
    background-image: url("${COMPOSITE}");
    background-size: cover;
    background-position: left center;
    background-repeat: no-repeat;
    border: none;
    border-radius: 14px;
    font-family: 'Noto Sans', 'JetBrainsMono Nerd Font', sans-serif;
}

#outer-box {
    margin: 0;
    padding: 14px;
    margin-left: ${WP_W}px;
    background-color: #1e1e1e;
    border-radius: 0 14px 14px 0;
}

#input {
    margin: 4px 4px 10px 4px;
    padding: 10px 14px;
    border: none;
    border-radius: 8px;
    background-color: #333333;
    color: #d8d8d8;
    font-size: 14px;
}

#input:focus {
    background-color: #3c3c3c;
    box-shadow: none;
}

#inner-box {
    margin: 0;
    padding: 0;
    background-color: transparent;
    border: none;
}

#scroll {
    margin: 0;
    padding: 0;
    background-color: transparent;
    border: none;
}

#entry {
    margin: 2px 4px;
    padding: 8px 10px;
    border-radius: 8px;
    background-color: transparent;
    color: #cccccc;
}

#entry:selected {
    background-color: rgba(160, 170, 180, 0.18);
    border: none;
    outline: none;
}

#text {
    color: #c8c8c8;
    font-size: 13px;
    margin-left: 4px;
}

#text:selected {
    color: #e8ecf0;
}

#img {
    margin-right: 10px;
}

/* Hide category expanders */
#expander {
    opacity: 0;
    margin: 0;
    padding: 0;
    width: 0;
    min-width: 0;
    min-height: 0;
}

#expander image {
    opacity: 0;
}
CSSEOF

# Kill any existing wofi instance
pkill wofi 2>/dev/null

# Launch wofi with generated style
wofi --conf "$STYLE_DIR/config" --style "$GENERATED_STYLE"
